experiment:
  name: test
  output_dir: output/${experiment.name}  # timestamp appended automatically

data:
  image_path: assets/argentina-flag.png
  canvas_size: [300, 256]  # width, height

renderer:
  backend: pillow

fitness:
  name: pixel_mse
  params: {}

selection:
  name: universal
  params: {}

crossover:
  name: uniform
  params: {}

mutation:
  name: gen
  params:
    point_sigma: 0.05
    color_sigma: 15.0

ga:
  pop_size: 50
  generations: 100
  elitism: 2
  maximize: false
  rho: 0.5  # generation gap (youth bias)

genome:
  num_triangles: 100

seed: 42